# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "masternode" => {"memory" => "2048", "cpu" => "2", "ip" => "100", "image" => "ubuntu/focal64"},
  "slave01" => {"memory" => "1024", "cpu" => "2", "ip" => "101", "image" => "ubuntu/focal64"},
  "slave02" => {"memory" => "1024", "cpu" => "2", "ip" => "102", "image" => "ubuntu/focal64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.fkztec.net"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Kubernet-Lab"]
        config.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y"
        if "#{conf["image"]}" == "ubuntu/focal64"
          machine.vm.provision "shell", path: "kuber.sh"
        end
        if "#{conf["image"]}" == "ubuntu/focal64"
          machine.vm.provision "shell", path: "containerd.sh"
        end
      end 
    end
  end
end
