# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master01" => {"memory" => "2048", "cpu" => "2", "ip" => "100", "image" => "ubuntu/focal64"},
  "node01" => {"memory" => "1024", "cpu" => "2", "ip" => "101", "image" => "ubuntu/focal64"},
  "node02" => {"memory" => "1024", "cpu" => "2", "ip" => "102", "image" => "ubuntu/focal64"}
  
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.fkztec.net"
      machine.vm.network "private_network", ip: "10.11.11.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Docker-Swarm"]
      end
      machine.vm.provision "shell", path: "docker.sh"
      if "#{conf["image"]}" == "ubuntu/focal64"
        machine.vm.provision "shell", inline: "sudo systemctl start docker && sudo systemctl enable docker"
      end
      
# Instalação do maste
      if "#{name}" == "master01"
        machine.vm.provision "shell", path: "master.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end