# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "ctlplane" => {"memory" => "2048", "cpu" => "2", "ip" => "200", "image" => "ubuntu/focal64"},
  "worker1" => {"memory" => "1024", "cpu" => "2", "ip" => "201", "image" => "ubuntu/focal64"},
  "worker2" => {"memory" => "1024", "cpu" => "2", "ip" => "202", "image" => "ubuntu/focal64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.fkztec.net"
      machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Docker_Swarm_Mao_na_Massa"]
      end
      machine.vm.provision "shell", path: "docker.sh"
      if "#{name}" == "contralplane"
        machine.vm.provision "shell", path: "contralplane.sh"
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end 